### ISSUE TITLE
The buttons for Refresh and Spectate are swapped

### ISSUE THREAD

**Issue by StrongSand94191** [Fcornaire/TF.EX#152]
The Spectate button displays the RT icon, but to trigger it you have to press LT.
The Refresh button displays the LT icon, but to trigger it you have to press RT.

(sorry about the discord ping in the video)

https://github.com/Fcornaire/TF.EX/assets/79473173/0b30f2aa-3f6d-434b-b908-9c72df6fbf55

**Comment by Fcornaire** [comment]
Fixed in #162
