### ISSUE TITLE
Replay inputs don't stop when the pause button is pressed

### ISSUE THREAD

**Issue by StrongSand94191** [Fcornaire/TF.EX#163]

**Comment by Fcornaire** [comment]
Already fixed , will be live in the next release

**Comment by Fcornaire** [comment]
Wait, i already merged that fixe in #160 
And tested right nowlast release 0.8.0 and didn't replicate it 
Can you check your plugin version ?

**Comment by StrongSand94191** [comment]
Sorry, I hadn't updated before I tested this bug :/
Thank you for the help!
