### ISSUE TITLE
Issues when exiting and reopening Quickplay

### ISSUE THREAD

**Issue by StrongSand94191** [Fcornaire/TF.EX#31]
If you exit the mode selection while selecting a mode other than Quickplay, such as Last Man Standing, and go back to Quickplay, then the player counter at the top left disappears. 

If you exit the mode selection while selecting Quickplay and reselect Versus, the mode will already be set to Quickplay and the player counter disappears. If you try and move the cursor upwards to change modes, the cursor will disappear. From here, you can't do anything except hit Z to exit the Quickplay screen, which (only sometimes) takes you to the archer select screen. This also shouldn't happen because the archer select screen should only show after you've already selected a mode. You also can't select an archer or use the arrow keys to change archers, only exit the menu.

I had many inconsistencies while trying to replicate this again, so expect weirdness.

<img width="1280" alt="Screenshot 2023-07-04 135701" src="https://github.com/Fcornaire/TF.EX/assets/79473173/117af264-6847-45b8-9ea1-47f9f911b9b4"> _The Quickplay screen without the player counter or the cursor shown._

**Comment by Fcornaire** [comment]
This is pretty old and can't be replicated with the new netplay mode
