### ISSUE TITLE
"Failed to Connect to Server" opens Archer Select, causing lots of bugs

### ISSUE THREAD

**Issue by StrongSand94191** [Fcornaire/TF.EX#32]
If you select Versus, sometimes you will get a "Failed to Connect to Server" message before selecting Quickplay. If you exit out of the message using the confirm button, then you get to the archer select screen. This shouldn't happen, as you haven't selected a mode yet. If two archers are selected, you can start the game. For some reason, players are required to choose teams, even if you were never in Team Deathmatch, and even if there are only two players. Then, a "Syncing" message appears at the top of the screen, and the game freezes, I assume because it's trying to connect two local players to the server. At this point the game softlocks.

<img width="1280" alt="Screenshot 2023-07-04 140658" src="https://github.com/Fcornaire/TF.EX/assets/79473173/17f4fe89-4559-4aec-887f-4f05ca823997"> _The softlocked game._

**Comment by Fcornaire** [comment]
Closing this since it's just related to #35 
Input should not happen if a Dialog is open
