### ISSUE TITLE
Trying to Sync is misspelled as "Trying to Sycnh" ingame

### ISSUE THREAD

**Issue by StrongSand94191** [Fcornaire/TF.EX#33]
When starting an online game, the message "Trying to Sycnh" displays. This should probably read "Trying to Sync."

<img width="1280" alt="image" src="https://github.com/Fcornaire/TF.EX/assets/79473173/9f5028b6-cd6c-4f65-b6a3-6c2da18c0082">

**Comment by Fcornaire** [comment]
fixed in #38
