### ISSUE TITLE
Input persists during "Failed to Connect to Server"

### ISSUE THREAD

**Issue by StrongSand94191** [Fcornaire/TF.EX#35]
Inputs can still happen, such as selecting a mode, while the "Failed to Connect to Server" message is displaying. For example, you can still use the arrow keys and the Z button (not the confirm button) to move through menus while this message is displaying.

**Comment by Fcornaire** [comment]
Note:
Input should not happen behind a dialog
So either block input if a Dialog is open but not optimal since it will also block Dialog interaction
Or try to only let Dialog catch input

**Comment by Fcornaire** [comment]
The mod doesn't use the Dialog anymore
